[package]
name = "amethyst-3d"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = {version="0.15.0", features=["vulkan", "no-slow-safety-checks"]}
amethyst_physics = "0.2.0"
amethyst_nphysics = "0.2.0"

[profile.dev]
debug = 0
